# Generated by Django 4.2 on 2025-11-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
