# Generated by Django 4.2 on 2025-11-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_studentprofile_parent_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
